//
// Created by J on 2017. 3. 7..
//

#ifndef A03_TYPE_LIB_H
#define A03_TYPE_LIB_H

#include <string>

using namespace std;

enum ErrorCode {
    REG_SUCCESS_NEW_SERVER = 1,
    REG_SUCCESS_EXISTING_SERVER = 2,
    REG_SAME_FUNCTION_EXIST = 3,
    FAILURE = -1,
    BINDER_ADDR_NOT_FOUND = -2,
    BINDER_PORT_NOT_FOUND = -3,
    BINDER_NOT_SETUP = -4,
    SERVER_SOCKET_NOT_SETUP = -5,
    SOCKET_NOT_SETUP = -6,
    SOCKET_CONNECTION_FAILED = -7,
    SOCKET_CONNECTION_FINISHED = -8,
    SOCKET_OPENING_FAILED = -9,
    DATA_SEND_FAILED = -10,
    READING_SOCKET_ERROR = -11,
    FUNCTION_SKELETON_DOES_NOT_EXIST_IN_THIS_SERVER = -12,
    FUNCTION_LOCATION_DOES_NOT_EXIST_IN_THIS_BINDER= -13,
    NO_HOST_FOUND = -14,
    ERROR_ON_LEASON = -15

};

#endif //A03_TYPE_LIB_H
